from codes.statInit import decompileAdvantages
from codes.statInit import decompileAttributes
from codes.statInit import decompileBasicStats
from codes.statInit import decompileContracts
from codes.statInit import decompileKiths
from codes.statInit import decompileMerits
from codes.statInit import decompilePowerStats
from codes.statInit import decompileSeemings
from codes.statInit import decompileSkills
from codes.statInit import decompileSphereStats