from codes.statInit import decompileAdvantages
from codes.statInit import decompileAttributes
from codes.statInit import decompileAuspices
from codes.statInit import decompileBasicStats
from codes.statInit import decompileClans
from codes.statInit import decompileCoils
from codes.statInit import decompileContracts
from codes.statInit import decompileCovenants
from codes.statInit import decompileCruac
from codes.statInit import decompileDevotions
from codes.statInit import decompileDisciplines
from codes.statInit import decompileGifts
from codes.statInit import decompileKiths
from codes.statInit import decompileMerits
from codes.statInit import decompileOrders
from codes.statInit import decompilePaths
from codes.statInit import decompilePowerStats
from codes.statInit import decompileRenown
from codes.statInit import decompileScales
from codes.statInit import decompileSeemings
from codes.statInit import decompileSkills
from codes.statInit import decompileSphereStats
from codes.statInit import decompileTheban
from codes.statInit import decompileTribes
from codes.statInit import decompileWerewolfRites